/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.PacienteBO;
import DTO.CitaViejoDTO;
import DTO.PerfilViejoDTO;
import Exception.NegocioException;
import configuracion.DependencyInjector;
import excepciones.PersistenciaException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sesion.SessionManager;

/**
 *
 * @author j_ama
 */
public class VerPerfilPaciente extends javax.swing.JFrame {
    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    private static VerPerfilPaciente instance;
    private PrincipalPaciente principalPacienteFrame;
    private EditarDatosPaciente editarDatosFrame;
    
    /**
     * Creates new form InicioDeSesion
     */
    public VerPerfilPaciente() throws NegocioException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Paciente - Ver perfil");
        mostrarPerfil();
    }
    
    public static VerPerfilPaciente getInstance() throws NegocioException {
         if (instance == null) {
            instance = new VerPerfilPaciente();
        }
        return instance;
    }

    public PrincipalPaciente getPrincipalPacienteFrame() {
        return principalPacienteFrame;
    }

    public void setPrincipalPacienteFrame(PrincipalPaciente principalPacienteFrame) {
        this.principalPacienteFrame = principalPacienteFrame;
    }

    public EditarDatosPaciente getEditarDatosFrame() {
        return editarDatosFrame;
    }

    public void setEditarDatosFrame(EditarDatosPaciente editarDatosFrame) {
        this.editarDatosFrame = editarDatosFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEditarDatos = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbNombre7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        lbNombre2 = new javax.swing.JLabel();
        lbNombre3 = new javax.swing.JLabel();
        lbNombre4 = new javax.swing.JLabel();
        lbNombre5 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbNombre8 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbEdad = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 222, 230));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setText("Mi perfil");

        btnEditarDatos.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarDatos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnEditarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDatos.setText("Editar datos");
        btnEditarDatos.setPreferredSize(new java.awt.Dimension(150, 30));
        btnEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setPreferredSize(new java.awt.Dimension(150, 30));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNombre7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbNombre7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombre7.setText("Dirección");
        lbNombre7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lbNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 50, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("Ficha de datos");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 130, 20));

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/iconPaciente.JPG")));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, 90));

        lbPerfil.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 20));

        lbNombre2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbNombre2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombre2.setText("Fecha de nacimiento");
        lbNombre2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lbNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, 20));

        lbNombre3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbNombre3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombre3.setText("Edad");
        lbNombre3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lbNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 50, -1));

        lbNombre4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbNombre4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombre4.setText("Teléfono");
        lbNombre4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lbNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 50, 20));

        lbNombre5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbNombre5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombre5.setText("Email");
        lbNombre5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lbNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 30, 20));

        lbFecha.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbFecha.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 180, 30));

        lbNombre8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbNombre8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombre8.setText("Nombre completo");
        jPanel2.add(lbNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, 20));

        lbNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombre.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 200, 30));

        lbTelefono.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTelefono.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 30));

        lbEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbEmail.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 180, 30));

        lbEdad.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbEdad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbEdad.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(lbEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 70, 30));

        lbDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDireccion.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 290, 30));

        lbFondo.setIcon(new ImageIcon(getClass().getResource("/fondoFicha.JPG")));
        lbFondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbFondo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 320));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        try {
            volver();
        } catch (NegocioException ex) {
            Logger.getLogger(VerPerfilPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosActionPerformed
        try {
            editarDatos();
        } catch (NegocioException ex) {
            Logger.getLogger(VerPerfilPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VerPerfilPaciente().setVisible(true);
                } catch (NegocioException ex) {
                    Logger.getLogger(VerPerfilPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre2;
    private javax.swing.JLabel lbNombre3;
    private javax.swing.JLabel lbNombre4;
    private javax.swing.JLabel lbNombre5;
    private javax.swing.JLabel lbNombre7;
    private javax.swing.JLabel lbNombre8;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbTelefono;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Obtiene los datos de perfil del paciente y los muestra.
     */
    public void mostrarPerfil() {
        try {
            // Intenta obtener el perfil
            PerfilViejoDTO perfil = pacienteBO.obtenerPerfilPaciente(SessionManager.getInstance().getUser());
            
            // Si no se encontró perfil
            if (perfil == null) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al mostrar perfil.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            // Si se encontró perfil
            else {
                // Mostrar los datos 
                lbPerfil.setText(perfil.getNombre());
                lbNombre.setText(perfil.getNombre() + " " + perfil.getApellidoPaterno() + " " + perfil.getApellidoMaterno());
                lbFecha.setText(perfil.getFechaNacimiento().toString());
                lbTelefono.setText(perfil.getTelefono());
                lbEmail.setText(perfil.getEmail());
                lbDireccion.setText(perfil.getDireccion().getCalle() + " " + perfil.getDireccion().getNumero() + " " + perfil.getDireccion().getColonia() + " " + perfil.getDireccion().getCodigoPostal());
                lbEdad.setText(String.valueOf(perfil.getEdad()));
            }
        } catch (NegocioException | PersistenciaException ex) {
            Logger.getLogger(VerPerfilPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Envía a pestaña de editar datos
     * @throws NegocioException Si hubo un error al cambiar de pestaña.
     */
    private void editarDatos() throws NegocioException {
        // Obtiene las citas activas del paciente
        List<CitaViejoDTO> citas = pacienteBO.obtenerCitasActivasPaciente(SessionManager.getInstance().getUser());
        
        // Si tiene citas activas
        if (!citas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No es posible editar datos si cuentas con citas activas.", "Error", JOptionPane.ERROR_MESSAGE);
        // Ir a ventana de editar datos
        } else {
            EditarDatosPaciente editarDatosPaciente = EditarDatosPaciente.getInstance();
            editarDatosPaciente.setVerPerfilPacienteFrame(this);
            editarDatosPaciente.setVisible(true);
            this.setVisible(false);
        }
    }
    
    /**
     * Envía a pestaña de menú principal de paciente
     * @throws NegocioException Si hubo un error al cambiar de pestaña.
     */
    private void volver() throws NegocioException {
        PrincipalPaciente principalPaciente = PrincipalPaciente.getInstance();
        principalPaciente.setVerPerfilPacienteFrame(this);
        principalPaciente.setVisible(true);
        this.setVisible(false);
    }
}